# Generated by Django 4.0.4 on 2022-05-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoDoanhSo',
            fields=[
                ('mabaocaodoanhso', models.AutoField(primary_key=True, serialize=False)),
                ('thoidiem', models.DateField(auto_now_add=True)),
                ('tongdoanhso', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CT_PhieuSuaChua',
            fields=[
                ('mact_phieusuachua', models.AutoField(primary_key=True, serialize=False)),
                ('solan', models.IntegerField()),
                ('tiencong', models.IntegerField()),
                ('noidung', models.CharField(max_length=100)),
                ('tongtien', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HieuXe',
            fields=[
                ('mahieuxe', models.AutoField(primary_key=True, serialize=False)),
                ('tenhieuxe', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('makhachhang', models.AutoField(primary_key=True, serialize=False)),
                ('tenkhachhang', models.CharField(max_length=40)),
                ('diachi', models.CharField(max_length=100)),
                ('dienthoai', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapVTPT',
            fields=[
                ('maphieunhapvtpt', models.AutoField(primary_key=True, serialize=False)),
                ('tongtien', models.IntegerField()),
                ('thoidiem', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThamSo',
            fields=[
                ('mathamso', models.AutoField(primary_key=True, serialize=False)),
                ('tenthamso', models.CharField(max_length=20)),
                ('giatri', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TienCong',
            fields=[
                ('matiencong', models.AutoField(primary_key=True, serialize=False)),
                ('tiencong', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VatTuPhuTung',
            fields=[
                ('mavattuphutung', models.AutoField(primary_key=True, serialize=False)),
                ('tenvattuphutung', models.CharField(max_length=50)),
                ('loaivattuphutung', models.CharField(max_length=50)),
                ('dongia', models.IntegerField()),
                ('soluong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('maxe', models.AutoField(primary_key=True, serialize=False)),
                ('bienso', models.CharField(max_length=20)),
                ('ngaytiepnhan', models.DateField(auto_now_add=True)),
                ('tienno', models.IntegerField(default=0)),
                ('mahieuxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.hieuxe')),
                ('makhachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuThuTien',
            fields=[
                ('maphieuthutien', models.AutoField(primary_key=True, serialize=False)),
                ('ngaythu', models.DateField(auto_now_add=True)),
                ('sotienthu', models.IntegerField()),
                ('maxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.xe')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuSuaChua',
            fields=[
                ('maphieusuachua', models.AutoField(primary_key=True, serialize=False)),
                ('tongthanhtien', models.IntegerField(default=0)),
                ('ngaylapphieu', models.DateField(auto_now_add=True)),
                ('maxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.xe')),
            ],
        ),
        migrations.CreateModel(
            name='CT_VatTuPhuTung',
            fields=[
                ('mact_vattuphutung', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField()),
                ('dongia', models.IntegerField()),
                ('tongthanhtien', models.IntegerField()),
                ('mact_phieusuachua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.ct_phieusuachua')),
                ('mavattuphutung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.vattuphutung')),
            ],
        ),
        migrations.AddField(
            model_name='ct_phieusuachua',
            name='maphieusuachua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.phieusuachua'),
        ),
        migrations.AddField(
            model_name='ct_phieusuachua',
            name='matiencong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.tiencong'),
        ),
        migrations.CreateModel(
            name='CT_PhieuNhapVTPT',
            fields=[
                ('mact_phieunhapvtpt', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField()),
                ('dongia', models.IntegerField()),
                ('maphieunhapvtpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.phieunhapvtpt')),
                ('mavattuphutung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.vattuphutung')),
            ],
        ),
        migrations.CreateModel(
            name='CT_BaoCaoDoanhSO',
            fields=[
                ('mact_baocaodoanhso', models.AutoField(primary_key=True, serialize=False)),
                ('luotsua', models.IntegerField(default=0)),
                ('thanhtien', models.IntegerField(default=0)),
                ('mabaocaodoanhso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.baocaodoanhso')),
                ('maphieusuachua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.phieusuachua')),
            ],
        ),
        migrations.CreateModel(
            name='BaoCaoTon',
            fields=[
                ('mabaocaoton', models.AutoField(primary_key=True, serialize=False)),
                ('tondau', models.IntegerField()),
                ('toncuoi', models.IntegerField()),
                ('phatsinh', models.IntegerField()),
                ('mavattuphutung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.vattuphutung')),
            ],
        ),
    ]
