# Generated by Django 3.0.5 on 2022-05-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='baocaoton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoidiem', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('makhachhang', models.AutoField(primary_key=True, serialize=False)),
                ('tenchuxe', models.CharField(max_length=40)),
                ('diachi', models.CharField(max_length=100)),
                ('dienthoai', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='THAMSO',
            fields=[
                ('TenThamSo', models.TextField(primary_key=True, serialize=False)),
                ('GiaTri', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='vattuphutung',
            fields=[
                ('mavattuphutung', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=40)),
                ('soluong', models.PositiveIntegerField()),
                ('dongia', models.PositiveIntegerField()),
            ],
        ),
    ]
