# Generated by Django 4.0.4 on 2022-05-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xe',
            name='bienso',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
