# Generated by Django 4.0.4 on 2022-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieusuachua',
            name='ngaylapphieu',
            field=models.DateField(),
        ),
    ]
