# Generated by Django 4.0.4 on 2022-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0002_alter_phieusuachua_ngaylapphieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='baocaodoanhso',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baocaodoanhso',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
