# Generated by Django 3.0.5 on 2022-05-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0002_baocaoton_khachhang_taikhoan_vattuphutung'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaiKhoan',
        ),
    ]
