# Generated by Django 4.0.4 on 2022-05-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0002_alter_xe_bienso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiencong',
            name='loaitiencong',
            field=models.CharField(default='', max_length=50),
        ),
    ]
