# Generated by Django 4.0.4 on 2022-05-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0003_tiencong_loaitiencong'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct_phieusuachua',
            name='tongtienvattu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiencong',
            name='loaitiencong',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
