# Generated by Django 4.0.4 on 2022-05-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0003_baocaodoanhso_month_baocaodoanhso_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ct_baocaodoanhso',
            name='mabaocaodoanhso',
        ),
    ]
