# Generated by Django 4.0.4 on 2022-05-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0004_ct_phieusuachua_tongtienvattu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieusuachua',
            name='tinhtrangthanhtoan',
            field=models.IntegerField(default=0),
        ),
    ]
