# Generated by Django 4.0.4 on 2022-05-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0004_remove_ct_baocaodoanhso_mabaocaodoanhso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ct_baocaodoanhso',
            name='mahieuxe',
        ),
        migrations.AddField(
            model_name='ct_baocaodoanhso',
            name='tenhieuxe',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ct_baocaodoanhso',
            name='ti_le',
            field=models.FloatField(default=0),
        ),
    ]
