# Generated by Django 4.0.4 on 2022-05-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0005_remove_ct_baocaodoanhso_mahieuxe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct_baocaodoanhso',
            name='STT',
            field=models.IntegerField(default=0),
        ),
    ]
