# Generated by Django 4.0.4 on 2022-05-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0005_phieusuachua_tinhtrangthanhtoan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieusuachua',
            name='tinhtrangthanhtoan',
            field=models.BooleanField(default=False),
        ),
    ]
