# Generated by Django 4.0.4 on 2022-05-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0006_alter_phieusuachua_tinhtrangthanhtoan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phieusuachua',
            name='tinhtrangthanhtoan',
        ),
    ]
