# Generated by Django 3.0.5 on 2022-05-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0006_auto_20220511_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default='Anonymous', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='User', max_length=10),
        ),
    ]
