# Generated by Django 4.0.4 on 2022-05-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0007_remove_phieusuachua_tinhtrangthanhtoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieusuachua',
            name='tinhtrangthutien',
            field=models.BooleanField(default=False),
        ),
    ]
