# Generated by Django 3.0.5 on 2022-05-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0008_auto_20220512_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emails',
            field=models.EmailField(default='anonymous@gmail.com', max_length=30),
        ),
    ]
