# Generated by Django 3.0.5 on 2022-05-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0009_customer_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/CustomerProfilePic/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='AnonymousUser', max_length=15, unique=True),
        ),
    ]
