# Generated by Django 3.0.5 on 2022-05-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0013_auto_20220517_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='emails',
            field=models.EmailField(default='anonymous@gmail.com', max_length=100, null=True),
        ),
    ]
