# Generated by Django 3.0.5 on 2022-05-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0017_staff_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoDoanhSo',
            fields=[
                ('mabaocaodoanhso', models.AutoField(primary_key=True, serialize=False)),
                ('thoidiem', models.DateField(auto_now_add=True)),
                ('tongdoanhso', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CT_BaoCaoDoanhSO',
            fields=[
                ('mact_baocaodoanhso', models.AutoField(primary_key=True, serialize=False)),
                ('luotsua', models.IntegerField(default=0)),
                ('thanhtien', models.IntegerField(default=0)),
                ('mabaocaodoanhso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.BaoCaoDoanhSo')),
            ],
        ),
        migrations.CreateModel(
            name='CT_PhieuNhapVTPT',
            fields=[
                ('mact_phieunhapvtpt', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField()),
                ('dongia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CT_PhieuSuaChua',
            fields=[
                ('mact_phieusuachua', models.AutoField(primary_key=True, serialize=False)),
                ('solan', models.IntegerField()),
                ('tiencong', models.IntegerField()),
                ('tongtienvattu', models.IntegerField(default=0)),
                ('noidung', models.CharField(max_length=100)),
                ('tongtien', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CT_VatTuPhuTung',
            fields=[
                ('mact_vattuphutung', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField()),
                ('dongia', models.IntegerField()),
                ('tongthanhtien', models.IntegerField()),
                ('mact_phieusuachua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.CT_PhieuSuaChua')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapVTPT',
            fields=[
                ('maphieunhapvtpt', models.AutoField(primary_key=True, serialize=False)),
                ('tongtien', models.IntegerField()),
                ('thoidiem', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuSuaChua',
            fields=[
                ('maphieusuachua', models.AutoField(primary_key=True, serialize=False)),
                ('tongthanhtien', models.IntegerField(default=0)),
                ('ngaylapphieu', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuThuTien',
            fields=[
                ('maphieuthutien', models.AutoField(primary_key=True, serialize=False)),
                ('ngaythu', models.DateField(auto_now_add=True)),
                ('sotienthu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThamSo',
            fields=[
                ('mathamso', models.AutoField(primary_key=True, serialize=False)),
                ('tenthamso', models.CharField(max_length=20)),
                ('giatri', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TienCong',
            fields=[
                ('matiencong', models.AutoField(primary_key=True, serialize=False)),
                ('loaitiencong', models.CharField(max_length=50, unique=True)),
                ('tiencong', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('maxe', models.AutoField(primary_key=True, serialize=False)),
                ('bienso', models.CharField(max_length=20, unique=True)),
                ('ngaytiepnhan', models.DateField(auto_now_add=True)),
                ('tienno', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='khachhang',
            old_name='tenchuxe',
            new_name='tenkhachhang',
        ),
        migrations.RenameField(
            model_name='vattuphutung',
            old_name='mavattuphutrung',
            new_name='mavattuphutung',
        ),
        migrations.RemoveField(
            model_name='baocaoton',
            name='MaPhuTung',
        ),
        migrations.RemoveField(
            model_name='baocaoton',
            name='PhatSinh',
        ),
        migrations.RemoveField(
            model_name='baocaoton',
            name='TonCuoi',
        ),
        migrations.RemoveField(
            model_name='baocaoton',
            name='TonDau',
        ),
        migrations.RemoveField(
            model_name='baocaoton',
            name='id',
        ),
        migrations.RemoveField(
            model_name='baocaoton',
            name='thang',
        ),
        migrations.RemoveField(
            model_name='hieuxe',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hieuxe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vattuphutung',
            name='ten',
        ),
        migrations.AddField(
            model_name='baocaoton',
            name='mabaocaoton',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baocaoton',
            name='mavattuphutung',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baocaoton',
            name='phatsinh',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baocaoton',
            name='toncuoi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baocaoton',
            name='tondau',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hieuxe',
            name='mahieuxe',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hieuxe',
            name='tenhieuxe',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khachhang',
            name='email',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vattuphutung',
            name='loaivattuphutung',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vattuphutung',
            name='tenvattuphutung',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='dienthoai',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vattuphutung',
            name='dongia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vattuphutung',
            name='soluong',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='PhieuTiepNhan',
        ),
        migrations.AddField(
            model_name='xe',
            name='mahieuxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.HieuXe'),
        ),
        migrations.AddField(
            model_name='xe',
            name='makhachhang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.KhachHang'),
        ),
        migrations.AddField(
            model_name='phieuthutien',
            name='maxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.Xe'),
        ),
        migrations.AddField(
            model_name='phieusuachua',
            name='maxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.Xe'),
        ),
        migrations.AddField(
            model_name='ct_vattuphutung',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AddField(
            model_name='ct_phieusuachua',
            name='maphieusuachua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.PhieuSuaChua'),
        ),
        migrations.AddField(
            model_name='ct_phieusuachua',
            name='matiencong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.TienCong'),
        ),
        migrations.AddField(
            model_name='ct_phieunhapvtpt',
            name='maphieunhapvtpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.PhieuNhapVTPT'),
        ),
        migrations.AddField(
            model_name='ct_phieunhapvtpt',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AddField(
            model_name='ct_baocaodoanhso',
            name='maphieusuachua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.PhieuSuaChua'),
        ),
    ]
