# Generated by Django 3.0.5 on 2022-05-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0019_auto_20220530_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='email',
        ),
        migrations.AlterField(
            model_name='baocaoton',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_phieunhapvtpt',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.CreateModel(
            name='PhieuTiepNhan',
            fields=[
                ('maphieutiepnhan', models.AutoField(primary_key=True, serialize=False)),
                ('tenchuxe', models.CharField(max_length=40)),
                ('bienso', models.PositiveIntegerField()),
                ('diachi', models.CharField(max_length=100)),
                ('dienthoai', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('hieuxe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gara.HieuXe')),
            ],
        ),
    ]
