# Generated by Django 3.0.5 on 2022-05-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0021_auto_20220530_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuyDinhHienHanh',
            fields=[
                ('MaThamSo', models.AutoField(primary_key=True, serialize=False)),
                ('TenThamSo', models.TextField(default='')),
                ('GiaTri', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ThamSo',
        ),
        migrations.RemoveField(
            model_name='ct_baocaodoanhso',
            name='mabaocaodoanhso',
        ),
        migrations.RemoveField(
            model_name='ct_baocaodoanhso',
            name='maphieusuachua',
        ),
        migrations.AddField(
            model_name='baocaodoanhso',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baocaodoanhso',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ct_baocaodoanhso',
            name='STT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ct_baocaodoanhso',
            name='tenhieuxe',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ct_baocaodoanhso',
            name='ti_le',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='baocaoton',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_phieunhapvtpt',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
    ]
