# Generated by Django 3.0.5 on 2022-05-30 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0024_auto_20220531_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vattuphutung',
            name='loaivattuphutung',
        ),
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaBCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.BaoCaoTon'),
        ),
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaVTPT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_phieunhapvtpt',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
    ]
