# Generated by Django 3.0.5 on 2022-05-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0025_auto_20220531_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baocaodoanhso',
            name='tongdoanhso',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ct_baocaodoanhso',
            name='thanhtien',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaBCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.BaoCaoTon'),
        ),
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaVTPT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_phieunhapvtpt',
            name='dongia',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ct_phieunhapvtpt',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_phieusuachua',
            name='tiencong',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='dongia',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='tongthanhtien',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hieuxe',
            name='tenhieuxe',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='phieunhapvtpt',
            name='tongtien',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='phieusuachua',
            name='tongthanhtien',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quydinhhienhanh',
            name='GiaTri',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tiencong',
            name='tiencong',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vattuphutung',
            name='dongia',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='xe',
            name='tienno',
            field=models.FloatField(default=0),
        ),
    ]
