# Generated by Django 3.0.5 on 2022-05-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0026_auto_20220531_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phieunhapvtpt',
            name='thoidiem',
        ),
        migrations.RemoveField(
            model_name='phieunhapvtpt',
            name='tongtien',
        ),
        migrations.AddField(
            model_name='phieunhapvtpt',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phieunhapvtpt',
            name='dongia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phieunhapvtpt',
            name='mavattuphutung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AddField(
            model_name='phieunhapvtpt',
            name='soluong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaBCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.BaoCaoTon'),
        ),
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaVTPT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.DeleteModel(
            name='CT_PhieuNhapVTPT',
        ),
    ]
