# Generated by Django 3.0.5 on 2022-05-31 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0027_auto_20220601_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baocaodoanhso',
            name='tongdoanhso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ct_baocaodoanhso',
            name='thanhtien',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaBCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.BaoCaoTon'),
        ),
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaVTPT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_phieusuachua',
            name='tiencong',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='dongia',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='tongthanhtien',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='phieunhapvtpt',
            name='mavattuphutung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='phieusuachua',
            name='tongthanhtien',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quydinhhienhanh',
            name='GiaTri',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiencong',
            name='tiencong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vattuphutung',
            name='dongia',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='xe',
            name='tienno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
